package top.andypage.page.webpage.Mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.andypage.page.webpage.model.ViewRecord;
import top.andypage.page.webpage.model.ViewRecordExample;

public interface ViewRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    long countByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int deleteByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int insert(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int insertSelective(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    List<ViewRecord> selectByExampleWithRowbounds(ViewRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    List<ViewRecord> selectByExample(ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    ViewRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") ViewRecord record, @Param("example") ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int updateByExample(@Param("record") ViewRecord record, @Param("example") ViewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int updateByPrimaryKeySelective(ViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWRECORD
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    int updateByPrimaryKey(ViewRecord record);
}