package top.andypage.page.webpage.model;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.ID
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TITLE
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.CREATE_TIME
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.MODIFIED_TIME
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Long modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.PUBLISHER_ID
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Long publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.COMMENT_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.VIEW_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.LIKE_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.TAG
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOPIC.DESCRIPTION
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.ID
     *
     * @return the value of TOPIC.ID
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.ID
     *
     * @param id the value for TOPIC.ID
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TITLE
     *
     * @return the value of TOPIC.TITLE
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TITLE
     *
     * @param title the value for TOPIC.TITLE
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.CREATE_TIME
     *
     * @return the value of TOPIC.CREATE_TIME
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.CREATE_TIME
     *
     * @param createTime the value for TOPIC.CREATE_TIME
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.MODIFIED_TIME
     *
     * @return the value of TOPIC.MODIFIED_TIME
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Long getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.MODIFIED_TIME
     *
     * @param modifiedTime the value for TOPIC.MODIFIED_TIME
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setModifiedTime(Long modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.PUBLISHER_ID
     *
     * @return the value of TOPIC.PUBLISHER_ID
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Long getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.PUBLISHER_ID
     *
     * @param publisherId the value for TOPIC.PUBLISHER_ID
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.COMMENT_COUNT
     *
     * @return the value of TOPIC.COMMENT_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.COMMENT_COUNT
     *
     * @param commentCount the value for TOPIC.COMMENT_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.VIEW_COUNT
     *
     * @return the value of TOPIC.VIEW_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.VIEW_COUNT
     *
     * @param viewCount the value for TOPIC.VIEW_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.LIKE_COUNT
     *
     * @return the value of TOPIC.LIKE_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.LIKE_COUNT
     *
     * @param likeCount the value for TOPIC.LIKE_COUNT
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.TAG
     *
     * @return the value of TOPIC.TAG
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.TAG
     *
     * @param tag the value for TOPIC.TAG
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOPIC.DESCRIPTION
     *
     * @return the value of TOPIC.DESCRIPTION
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOPIC.DESCRIPTION
     *
     * @param description the value for TOPIC.DESCRIPTION
     *
     * @mbg.generated Tue Apr 07 21:47:37 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}