package top.andypage.page.webpage.model;

public class ViewRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWRECORD.ID
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWRECORD.USERID
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIEWRECORD.TOPICIDS
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    private String topicids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWRECORD.ID
     *
     * @return the value of VIEWRECORD.ID
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWRECORD.ID
     *
     * @param id the value for VIEWRECORD.ID
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWRECORD.USERID
     *
     * @return the value of VIEWRECORD.USERID
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWRECORD.USERID
     *
     * @param userid the value for VIEWRECORD.USERID
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIEWRECORD.TOPICIDS
     *
     * @return the value of VIEWRECORD.TOPICIDS
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    public String getTopicids() {
        return topicids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIEWRECORD.TOPICIDS
     *
     * @param topicids the value for VIEWRECORD.TOPICIDS
     *
     * @mbg.generated Sun Apr 12 13:45:38 CST 2020
     */
    public void setTopicids(String topicids) {
        this.topicids = topicids == null ? null : topicids.trim();
    }
}